In [1]:
from fastai.conv_learner import *
PATH = 'data/dogscats/'
sz=224

In [2]:
tfms = tfms_from_model(resnet50, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
data = ImageClassifierData.from_paths(PATH, tfms=tfms)
learn = ConvLearner.pretrained(resnet50, data)

%time learn.fit(1e-2, 3, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.03901  0.02676  0.98926]                         
[ 1.       0.03971  0.02543  0.98926]                         
[ 2.       0.02977  0.02543  0.98926]                         

CPU times: user 14min 5s, sys: 2min 9s, total: 16min 14s
Wall time: 8min 9s


In [3]:
learn.unfreeze()
learn.bn_freeze(True)
# if architecture is greater than resnet34 (i.e. resnet50 or resnext101)
# if dataset is similar to imagenet (side on images, standard objects, similar size)
# causing batch normalization - moving averages to not be updated

%time learn.fit([1e-5, 1e-4, 1e-2], 1, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=1), HTML(value='')))

[ 0.       0.02846  0.02357  0.9917 ]                         

CPU times: user 9min 20s, sys: 1min 14s, total: 10min 34s
Wall time: 7min 51s


In [ ]:
%time log_preds,y = learn.TTA()

In [14]:
probs = np.mean(np.exp(log_preds),0)
metrics.log_loss(y, probs), accuracy(probs,y)

(0.017752404270271901, 0.99399999999999999)